name: Build and Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (if you're using Node)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci

    - name: Build app
      run: |
        echo "Building the app..."
        npm run build
        echo "Build complete."

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Google App Engine
      run: |
        echo "Deploying to GAE..."
        gcloud app deploy --quiet --project=$GCP_PROJECT_ID --region=$GAE_REGION
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GAE_REGION: ${{ secrets.GAE_REGION }}
